### GET request to example server
POST http://localhost:8080/api/resources
Content-Type: application/json

{
  "name": "Meeting Room B",
  "description": "Large meeting room on 2nd floor",
  "location": "Floor 2",
  "type": "ROOM"
}

###
GET http://localhost:8080/api/resources?page=0&size=101